server:
  port: 11000

spring:
  profiles:
    default: local

spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        default_batch_fetch_size: '100'
        format_sql: 'true'
        use_sql_comments: 'true'
    generate-ddl: 'false'
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'