server:
  port: 11000


  # Chat address
  address: 0.0.0.0

spring:

  profiles:
#    default: local
    default: prod

  jpa:
    open-in-view: 'false'
    show-sql: 'true'
    generate-ddl: true
    properties:
      hibernate:
        default_batch_fetch_size: '100'
        format_sql: 'true'
        use_sql_comments: 'true'

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
